name = "AffineRegions"
uuid = "1fb9d175-a4f8-4e64-b312-fdb4d54c7e1f"
version = "0.1.0"
authors = ["Klamkin, Michael <mklamkin3@gatech.edu>"]

[deps]
DiffOpt = "930fe3bc-9c6b-11ea-2d94-6184641e85e7"
Dualization = "191a621a-6537-11e9-281d-650236a99e60"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"

[compat]
DiffOpt = "0.5"
Dualization = "0.7"
JuMP = "1.29"

[extras]
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "HiGHS"]
